### ISSUE TITLE
Battlefront 1 .wld import

### ISSUE THREAD

**Issue by NDRWhun** [Ben1138/Unity-SWBF2-Import#2]
It recognise the bf1 .wld files. I've checked the world file and it contains the right data of object and it's original places with coords. But when I open with the importer then it could not read out the most of the data. I think It's because the layer files. Can you fix it later? :) I have to import files one by one and do copy paste things of every single coords. 

Thank you mate! It's an awesome tool. Keep it up!

Andrew.

**Comment by Ben1138** [comment]
Currently .wld and .lyr files are just being parsed via a regular expression. I guess in Battlefront 1 the files slighty differ so the parsing breaks for some objects. If that is the case it's a problem within LibSWBF2, not the unity importer. But since I stopped developing on the C# version (I started a C++ version instead) this might take a while.
Anyway, you are welcome to do a Pull Request on the C# version of LibSWBF2 ;)

**Comment by NDRWhun** [comment]
Okay. I'll check it out. I'm trying to figure out why the Coruscant objects are loading weird or missing. 
1 year ago I'm tried to export models as .obj and drop into Unity. It worked like this. The .MSHs had the "correct" position and rotating. It was painful. But the results was the same with your Importer. I don't know where's the problem. I'm trying my best :D It's a good practice for me. I can read the code and understand but cannot write a single line of code :(.
